# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.supplementary import supplementary_pb2 as supplementary__pb2


class SupplementarysStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSupplementary = channel.unary_unary(
                '/Supplementarys/CreateSupplementary',
                request_serializer=supplementary__pb2.CreateSupplementaryRequest.SerializeToString,
                response_deserializer=supplementary__pb2.CreateSupplementaryResponse.FromString,
                )
        self.GetSupplementary = channel.unary_unary(
                '/Supplementarys/GetSupplementary',
                request_serializer=supplementary__pb2.GetSupplementaryRequest.SerializeToString,
                response_deserializer=supplementary__pb2.GetSupplementaryResponse.FromString,
                )


class SupplementarysServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSupplementary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSupplementary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SupplementarysServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSupplementary': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSupplementary,
                    request_deserializer=supplementary__pb2.CreateSupplementaryRequest.FromString,
                    response_serializer=supplementary__pb2.CreateSupplementaryResponse.SerializeToString,
            ),
            'GetSupplementary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupplementary,
                    request_deserializer=supplementary__pb2.GetSupplementaryRequest.FromString,
                    response_serializer=supplementary__pb2.GetSupplementaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Supplementarys', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Supplementarys(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSupplementary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Supplementarys/CreateSupplementary',
            supplementary__pb2.CreateSupplementaryRequest.SerializeToString,
            supplementary__pb2.CreateSupplementaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSupplementary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Supplementarys/GetSupplementary',
            supplementary__pb2.GetSupplementaryRequest.SerializeToString,
            supplementary__pb2.GetSupplementaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
