# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: supplementary.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='supplementary.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13supplementary.proto\"O\n\x1a\x43reateSupplementaryRequest\x12\x10\n\x08owner_id\x18\x01 \x01(\x05\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x12\n\nsubject_id\x18\x03 \x01(\t\"-\n\x17GetSupplementaryRequest\x12\x12\n\nsubject_id\x18\x03 \x01(\t\"B\n\rSupplementary\x12\x10\n\x08owner_id\x18\x01 \x01(\x05\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x12\n\nsubject_id\x18\x03 \x01(\t\"B\n\x18GetSupplementaryResponse\x12&\n\x0esupplementarys\x18\x01 \x03(\x0b\x32\x0e.Supplementary\"6\n\x1b\x43reateSupplementaryResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t2\xab\x01\n\x0eSupplementarys\x12P\n\x13\x43reateSupplementary\x12\x1b.CreateSupplementaryRequest\x1a\x1c.CreateSupplementaryResponse\x12G\n\x10GetSupplementary\x12\x18.GetSupplementaryRequest\x1a\x19.GetSupplementaryResponseb\x06proto3'
)




_CREATESUPPLEMENTARYREQUEST = _descriptor.Descriptor(
  name='CreateSupplementaryRequest',
  full_name='CreateSupplementaryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner_id', full_name='CreateSupplementaryRequest.owner_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='CreateSupplementaryRequest.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subject_id', full_name='CreateSupplementaryRequest.subject_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=102,
)


_GETSUPPLEMENTARYREQUEST = _descriptor.Descriptor(
  name='GetSupplementaryRequest',
  full_name='GetSupplementaryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject_id', full_name='GetSupplementaryRequest.subject_id', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=149,
)


_SUPPLEMENTARY = _descriptor.Descriptor(
  name='Supplementary',
  full_name='Supplementary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner_id', full_name='Supplementary.owner_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='Supplementary.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subject_id', full_name='Supplementary.subject_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=217,
)


_GETSUPPLEMENTARYRESPONSE = _descriptor.Descriptor(
  name='GetSupplementaryResponse',
  full_name='GetSupplementaryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='supplementarys', full_name='GetSupplementaryResponse.supplementarys', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=285,
)


_CREATESUPPLEMENTARYRESPONSE = _descriptor.Descriptor(
  name='CreateSupplementaryResponse',
  full_name='CreateSupplementaryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CreateSupplementaryResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='CreateSupplementaryResponse.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=341,
)

_GETSUPPLEMENTARYRESPONSE.fields_by_name['supplementarys'].message_type = _SUPPLEMENTARY
DESCRIPTOR.message_types_by_name['CreateSupplementaryRequest'] = _CREATESUPPLEMENTARYREQUEST
DESCRIPTOR.message_types_by_name['GetSupplementaryRequest'] = _GETSUPPLEMENTARYREQUEST
DESCRIPTOR.message_types_by_name['Supplementary'] = _SUPPLEMENTARY
DESCRIPTOR.message_types_by_name['GetSupplementaryResponse'] = _GETSUPPLEMENTARYRESPONSE
DESCRIPTOR.message_types_by_name['CreateSupplementaryResponse'] = _CREATESUPPLEMENTARYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateSupplementaryRequest = _reflection.GeneratedProtocolMessageType('CreateSupplementaryRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATESUPPLEMENTARYREQUEST,
  '__module__' : 'supplementary_pb2'
  # @@protoc_insertion_point(class_scope:CreateSupplementaryRequest)
  })
_sym_db.RegisterMessage(CreateSupplementaryRequest)

GetSupplementaryRequest = _reflection.GeneratedProtocolMessageType('GetSupplementaryRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSUPPLEMENTARYREQUEST,
  '__module__' : 'supplementary_pb2'
  # @@protoc_insertion_point(class_scope:GetSupplementaryRequest)
  })
_sym_db.RegisterMessage(GetSupplementaryRequest)

Supplementary = _reflection.GeneratedProtocolMessageType('Supplementary', (_message.Message,), {
  'DESCRIPTOR' : _SUPPLEMENTARY,
  '__module__' : 'supplementary_pb2'
  # @@protoc_insertion_point(class_scope:Supplementary)
  })
_sym_db.RegisterMessage(Supplementary)

GetSupplementaryResponse = _reflection.GeneratedProtocolMessageType('GetSupplementaryResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSUPPLEMENTARYRESPONSE,
  '__module__' : 'supplementary_pb2'
  # @@protoc_insertion_point(class_scope:GetSupplementaryResponse)
  })
_sym_db.RegisterMessage(GetSupplementaryResponse)

CreateSupplementaryResponse = _reflection.GeneratedProtocolMessageType('CreateSupplementaryResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATESUPPLEMENTARYRESPONSE,
  '__module__' : 'supplementary_pb2'
  # @@protoc_insertion_point(class_scope:CreateSupplementaryResponse)
  })
_sym_db.RegisterMessage(CreateSupplementaryResponse)



_SUPPLEMENTARYS = _descriptor.ServiceDescriptor(
  name='Supplementarys',
  full_name='Supplementarys',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=344,
  serialized_end=515,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateSupplementary',
    full_name='Supplementarys.CreateSupplementary',
    index=0,
    containing_service=None,
    input_type=_CREATESUPPLEMENTARYREQUEST,
    output_type=_CREATESUPPLEMENTARYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSupplementary',
    full_name='Supplementarys.GetSupplementary',
    index=1,
    containing_service=None,
    input_type=_GETSUPPLEMENTARYREQUEST,
    output_type=_GETSUPPLEMENTARYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUPPLEMENTARYS)

DESCRIPTOR.services_by_name['Supplementarys'] = _SUPPLEMENTARYS

# @@protoc_insertion_point(module_scope)
